### ISSUE TITLE
Support popupover/help text over agent lines

### ISSUE THREAD

**Issue by anuragvohraec** [davidje13/SequenceDiagram#61]
In case of very large sequence diagram, it would be really helpfull to have popups/help text over agent lines, showing there Agent name.
Currently for large sequence diagram the opening and closing box go out of viewport, and one need to again and again scroll up to see which line belings to which agent.

**Comment by davidje13** [comment]
This is an interesting one;

SVG doesn't have a native way to show tooltips for individual elements, nor does it have an equivalent to `position: sticky`, so anything interactive here would need to be custom. Currently the only real interactivity in the diagrams is opening/closing groups, which is achieved by updating state and re-rendering.

This would be a different kind of interactivity, because it would need live interaction (without a full re-render of the diagram itself). And since SVG doesn't have native elements for it, it would only be possible inside the editor (and in any projects which use the library to render a diagram), but would _not_ work for exported diagrams (PNG / SVG / even URL).

A possible non-interactive alternative would be to have some new command available (maybe `relabel`?) which displays the agent name boxes at the current position. As an editor, you could then use this command periodically throughout your diagram. It's possible to approximate this already (but with some verbose syntax and the wrong shapes):

```
Foo -> Bar: message 1

# repeat all the agent names on their lines:
state over Foo: Foo
& state over Bar: Bar

Bar -> Foo: message 2
```

If going that route, I could imagine situations where editors would want to repeat the names of some agents but not others, so perhaps it would be good to follow the existing syntax for `define`, `begin`, and `end` by allowing an agent list at the end:

```
Foo -> Bar: message 1

# re-label all currently visible agent lines
relabel

Bar -> Foo: message 2

# only re-label the "Foo" and "Other" agent lines
relabel Foo, Other
```

Other possible approaches might be:
- consider this as a new type of `divider` (e.g. `divider names`) but that might be a bit of a weird mental model, and wouldn't cover the use-case of only re-labeling some agents;
- a new type of `note` (e.g. `note names over Foo, Bar`) but since they wouldn't take a label they would be quite different from existing notes.

---

I'd be interested to know if the non-interactive version would work for you, or if you're really looking for something dynamic (with the caveat that it won't work when exported as an image)

**Comment by anuragvohraec** [comment]
* The solution `state over Foo: Foo`, pretty much solves the problem for me.

* And you are correct keeping it non-interactive makes things simple and exportable. 
The exported SVG and PNG can have the same benefits, which otherwise in an interactive solution would only work in the tool or svg (with script embeded). So I will vouch for the non-interactive route.

* Regarding reintroducing the new command, yes do introduce it in your future release. As a new command would make the text script much more reasonable , rather than a work around like `state over Foo:Foo`. I will like to suggest this new command name to be  like this:

```
begin E1, E2, E3

#new command suggestion
continue E1,E2

end E1,E2,E3
```

**Comment by davidje13** [comment]
`relabel` added in d718c9c13efdd22d1dbf075ad2fd10f13a8ac6cd (might take a few minutes to get deployed)

Hope it helps! Let me know if you spot any issues with it.

**Comment by anuragvohraec** [comment]
I will test and reply. Thank you.

**Comment by anuragvohraec** [comment]
Hi there,

Its working as expected. Thank you.

One more suggestion I have is to add service worker so it works even offline.
